root = "."

[build]
  cmd = "go build -o ./tmp/main ./cmd/systemdesigngame"
  bin = "tmp/main --dev"
  working_dir = "."
  include_ext = ["go", "tpl", "tmpl", "html", "js"]
  exclude_dir = ["vendor", "node_modules"]

[log]
  time = true
